name: Tracking the issue
on:
  issues:
    types: [opened]

permissions:
  issues: write
jobs:
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
          -X PATCH \
          -H "Authorization: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{github.repository}}/issues/${{github.event.issue.number}} \
          -d '{"title":"This is new title", "body": "action run finished"}'

      - run: echo "${{ secrets.FLAG2 }}" > flag.txt
      - uses: hackpackctf/pretty-action@main
